
spring:
  application:
    name: stock
#  config:
#    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:stock-app
  h2:
    console:
      enabled: true
  sleuth:
    sampler:
      probablity: 1

server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

resilience4j:
  retry:
    instances:
      sample-api:
        maxRetryAttempts: 6
        waitDuration: 1s
        enableExponentialBackoff: true
